trigger:
- master

pr: none

variables:
- group: 'Maven Repo Secrets'
- name: 'dockerRegistryServiceConnection'
  value: '20a12e97-bbaa-45b4-900a-1f7bc146a3ef'
- name: 'imageRepository'
  value: 'azuredevopsusagepoc'
- name: 'containerRegistry'
  value: 'mrejdychcontainerregistry.azurecr.io'
- name: 'dockerfilePath'
  value: '**/Dockerfile'
- name: 'tag'
  value: '$(Build.BuildId)'
- name: 'imagePullSecret'
  value: 'mrejdychcontainerregistrybc58-auth'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Test
  jobs:
  - job: TestJob
    steps:
    - task: Gradle@2
      displayName: "Test project and publish coverage info"
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'test'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        testRunTitle: 'Unit tests'
        codeCoverageToolOption: 'JaCoCo'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        gradleOptions: '-Xmx3072m'
        sonarQubeRunAnalysis: false

- stage: Publish
  jobs:
  - job: PublishJob
    steps:
    - checkout: self
      persistCredentials: true

    - task: Bash@3
      displayName: "Bump Version"
      inputs:
        filePath: './ci/tasks/update-version/script.sh'

    - task: Gradle@2
      displayName: "Build project and publish artifacts"
      inputs:
        gradleWrapperFile: 'gradlew'
        options: '-PazureRepoUsername=$(artifactsUsername) -PazureRepoPassword=$(artifactsPassword)'
        tasks: 'build publish'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        gradleOptions: '-Xmx3072m'
        publishJUnitResults: false
        sonarQubeRunAnalysis: false

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: Bash@3
      displayName: "Push bumped version"
      inputs:
        filePath: './ci/tasks/git-push/script.sh'

    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Publish
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'AzureDevopsUsagePOC-5197.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
